#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("RssReader2.Resource", IsApplication=true)]

namespace RssReader2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circleColor = global::RssReader2.Resource.Attribute.circleColor;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circularProgressBarStyle = global::RssReader2.Resource.Attribute.circularProgressBarStyle;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_gravity = global::RssReader2.Resource.Attribute.circular_gravity;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_indeterminate = global::RssReader2.Resource.Attribute.circular_indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_indeterminate_interval = global::RssReader2.Resource.Attribute.circular_indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_marker_progress = global::RssReader2.Resource.Attribute.circular_marker_progress;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_progress = global::RssReader2.Resource.Attribute.circular_progress;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_progress_background_color = global::RssReader2.Resource.Attribute.circular_progress_background_color;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_progress_color = global::RssReader2.Resource.Attribute.circular_progress_color;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_stroke_width = global::RssReader2.Resource.Attribute.circular_stroke_width;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.indeterminate = global::RssReader2.Resource.Attribute.indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.indeterminate_interval = global::RssReader2.Resource.Attribute.indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.innerSize = global::RssReader2.Resource.Attribute.innerSize;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.max = global::RssReader2.Resource.Attribute.max;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.pinned = global::RssReader2.Resource.Attribute.pinned;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.pinnedDrawable = global::RssReader2.Resource.Attribute.pinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.progress = global::RssReader2.Resource.Attribute.progress;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.progressButtonStyle = global::RssReader2.Resource.Attribute.progressButtonStyle;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.progressColor = global::RssReader2.Resource.Attribute.progressColor;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.shadowDrawable = global::RssReader2.Resource.Attribute.shadowDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.unpinnedDrawable = global::RssReader2.Resource.Attribute.unpinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Color.progress_default_circle_color = global::RssReader2.Resource.Color.progress_default_circle_color;
			global::com.refractored.monodroidtoolkit.Resource.Color.progress_default_progress_color = global::RssReader2.Resource.Color.progress_default_progress_color;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_dark = global::RssReader2.Resource.Color.refractored_background_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_holo_dark = global::RssReader2.Resource.Color.refractored_background_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_holo_light = global::RssReader2.Resource.Color.refractored_background_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_light = global::RssReader2.Resource.Color.refractored_background_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_dark = global::RssReader2.Resource.Color.refractored_bright_foreground_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_dark_disabled = global::RssReader2.Resource.Color.refractored_bright_foreground_dark_disabled;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_disabled_holo_dark = global::RssReader2.Resource.Color.refractored_bright_foreground_disabled_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_disabled_holo_light = global::RssReader2.Resource.Color.refractored_bright_foreground_disabled_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_holo_dark = global::RssReader2.Resource.Color.refractored_bright_foreground_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_holo_light = global::RssReader2.Resource.Color.refractored_bright_foreground_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_light = global::RssReader2.Resource.Color.refractored_bright_foreground_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_disabled_holo_dark = global::RssReader2.Resource.Color.refractored_dim_foreground_disabled_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_disabled_holo_light = global::RssReader2.Resource.Color.refractored_dim_foreground_disabled_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_holo_dark = global::RssReader2.Resource.Color.refractored_dim_foreground_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_holo_light = global::RssReader2.Resource.Color.refractored_dim_foreground_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_highlighted_text_holo_dark = global::RssReader2.Resource.Color.refractored_highlighted_text_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_highlighted_text_holo_light = global::RssReader2.Resource.Color.refractored_highlighted_text_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_hint_foreground_holo_dark = global::RssReader2.Resource.Color.refractored_hint_foreground_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_hint_foreground_holo_light = global::RssReader2.Resource.Color.refractored_hint_foreground_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_blue_bright = global::RssReader2.Resource.Color.refractored_holo_blue_bright;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_blue_dark = global::RssReader2.Resource.Color.refractored_holo_blue_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_blue_light = global::RssReader2.Resource.Color.refractored_holo_blue_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_green_dark = global::RssReader2.Resource.Color.refractored_holo_green_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_green_light = global::RssReader2.Resource.Color.refractored_holo_green_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_orange_dark = global::RssReader2.Resource.Color.refractored_holo_orange_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_orange_light = global::RssReader2.Resource.Color.refractored_holo_orange_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_purple = global::RssReader2.Resource.Color.refractored_holo_purple;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_red_dark = global::RssReader2.Resource.Color.refractored_holo_red_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_red_light = global::RssReader2.Resource.Color.refractored_holo_red_light;
			global::com.refractored.monodroidtoolkit.Resource.Dimension.progress_inner_size = global::RssReader2.Resource.Dimension.progress_inner_size;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.pin_progress_pinned = global::RssReader2.Resource.Drawable.pin_progress_pinned;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.pin_progress_shadow = global::RssReader2.Resource.Drawable.pin_progress_shadow;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.pin_progress_unpinned = global::RssReader2.Resource.Drawable.pin_progress_unpinned;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.scrubber_control_normal_holo = global::RssReader2.Resource.Drawable.scrubber_control_normal_holo;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.scrubber_control_pressed_holo = global::RssReader2.Resource.Drawable.scrubber_control_pressed_holo;
			global::com.refractored.monodroidtoolkit.Resource.Id.bottom = global::RssReader2.Resource.Id.bottom;
			global::com.refractored.monodroidtoolkit.Resource.Id.center = global::RssReader2.Resource.Id.center;
			global::com.refractored.monodroidtoolkit.Resource.Id.center_horizontal = global::RssReader2.Resource.Id.center_horizontal;
			global::com.refractored.monodroidtoolkit.Resource.Id.center_vertical = global::RssReader2.Resource.Id.center_vertical;
			global::com.refractored.monodroidtoolkit.Resource.Id.clip = global::RssReader2.Resource.Id.clip;
			global::com.refractored.monodroidtoolkit.Resource.Id.clip_horizontal = global::RssReader2.Resource.Id.clip_horizontal;
			global::com.refractored.monodroidtoolkit.Resource.Id.clip_vertical = global::RssReader2.Resource.Id.clip_vertical;
			global::com.refractored.monodroidtoolkit.Resource.Id.end = global::RssReader2.Resource.Id.end;
			global::com.refractored.monodroidtoolkit.Resource.Id.fill = global::RssReader2.Resource.Id.fill;
			global::com.refractored.monodroidtoolkit.Resource.Id.fill_horizontal = global::RssReader2.Resource.Id.fill_horizontal;
			global::com.refractored.monodroidtoolkit.Resource.Id.fill_vertical = global::RssReader2.Resource.Id.fill_vertical;
			global::com.refractored.monodroidtoolkit.Resource.Id.left = global::RssReader2.Resource.Id.left;
			global::com.refractored.monodroidtoolkit.Resource.Id.right = global::RssReader2.Resource.Id.right;
			global::com.refractored.monodroidtoolkit.Resource.Id.start = global::RssReader2.Resource.Id.start;
			global::com.refractored.monodroidtoolkit.Resource.Id.top = global::RssReader2.Resource.Id.top;
			global::com.refractored.monodroidtoolkit.Resource.Integer.circular_indeterminent_interval = global::RssReader2.Resource.Integer.circular_indeterminent_interval;
			global::com.refractored.monodroidtoolkit.Resource.Integer.progressbutton_indeterminent_interval = global::RssReader2.Resource.Integer.progressbutton_indeterminent_interval;
			global::com.refractored.monodroidtoolkit.Resource.Style.CircularProgressBar = global::RssReader2.Resource.Style.CircularProgressBar;
			global::com.refractored.monodroidtoolkit.Resource.Style.CircularProgressBarLight = global::RssReader2.Resource.Style.CircularProgressBarLight;
			global::com.refractored.monodroidtoolkit.Resource.Style.ProgressButton = global::RssReader2.Resource.Style.ProgressButton;
			global::com.refractored.monodroidtoolkit.Resource.Style.ProgressButton_Pin = global::RssReader2.Resource.Style.ProgressButton_Pin;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar = global::RssReader2.Resource.Styleable.HoloCircularProgressBar;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_gravity = global::RssReader2.Resource.Styleable.HoloCircularProgressBar_circular_gravity;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate = global::RssReader2.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate_interval = global::RssReader2.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_marker_progress = global::RssReader2.Resource.Styleable.HoloCircularProgressBar_circular_marker_progress;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_progress = global::RssReader2.Resource.Styleable.HoloCircularProgressBar_circular_progress;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_progress_background_color = global::RssReader2.Resource.Styleable.HoloCircularProgressBar_circular_progress_background_color;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_progress_color = global::RssReader2.Resource.Styleable.HoloCircularProgressBar_circular_progress_color;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_stroke_width = global::RssReader2.Resource.Styleable.HoloCircularProgressBar_circular_stroke_width;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton = global::RssReader2.Resource.Styleable.ProgressButton;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_android_clickable = global::RssReader2.Resource.Styleable.ProgressButton_android_clickable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_android_focusable = global::RssReader2.Resource.Styleable.ProgressButton_android_focusable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_android_selectableItemBackground = global::RssReader2.Resource.Styleable.ProgressButton_android_selectableItemBackground;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_circleColor = global::RssReader2.Resource.Styleable.ProgressButton_circleColor;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_indeterminate = global::RssReader2.Resource.Styleable.ProgressButton_indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_indeterminate_interval = global::RssReader2.Resource.Styleable.ProgressButton_indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_innerSize = global::RssReader2.Resource.Styleable.ProgressButton_innerSize;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_max = global::RssReader2.Resource.Styleable.ProgressButton_max;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_pinned = global::RssReader2.Resource.Styleable.ProgressButton_pinned;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_pinnedDrawable = global::RssReader2.Resource.Styleable.ProgressButton_pinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_progress = global::RssReader2.Resource.Styleable.ProgressButton_progress;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_progressColor = global::RssReader2.Resource.Styleable.ProgressButton_progressColor;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_shadowDrawable = global::RssReader2.Resource.Styleable.ProgressButton_shadowDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_unpinnedDrawable = global::RssReader2.Resource.Styleable.ProgressButton_unpinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.Theme = global::RssReader2.Resource.Styleable.Theme;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.Theme_circularProgressBarStyle = global::RssReader2.Resource.Styleable.Theme_circularProgressBarStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.centered = global::RssReader2.Resource.Attribute.centered;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.clipPadding = global::RssReader2.Resource.Attribute.clipPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.fadeDelay = global::RssReader2.Resource.Attribute.fadeDelay;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.fadeLength = global::RssReader2.Resource.Attribute.fadeLength;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.fades = global::RssReader2.Resource.Attribute.fades;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.fillColor = global::RssReader2.Resource.Attribute.fillColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerColor = global::RssReader2.Resource.Attribute.footerColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerIndicatorHeight = global::RssReader2.Resource.Attribute.footerIndicatorHeight;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerIndicatorStyle = global::RssReader2.Resource.Attribute.footerIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerIndicatorUnderlinePadding = global::RssReader2.Resource.Attribute.footerIndicatorUnderlinePadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerLineHeight = global::RssReader2.Resource.Attribute.footerLineHeight;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerPadding = global::RssReader2.Resource.Attribute.footerPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.gapWidth = global::RssReader2.Resource.Attribute.gapWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.linePosition = global::RssReader2.Resource.Attribute.linePosition;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.lineWidth = global::RssReader2.Resource.Attribute.lineWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.pageColor = global::RssReader2.Resource.Attribute.pageColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.radius = global::RssReader2.Resource.Attribute.radius;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.selectedBold = global::RssReader2.Resource.Attribute.selectedBold;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.selectedColor = global::RssReader2.Resource.Attribute.selectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.snap = global::RssReader2.Resource.Attribute.snap;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.strokeColor = global::RssReader2.Resource.Attribute.strokeColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.strokeWidth = global::RssReader2.Resource.Attribute.strokeWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.titlePadding = global::RssReader2.Resource.Attribute.titlePadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.topPadding = global::RssReader2.Resource.Attribute.topPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.unselectedColor = global::RssReader2.Resource.Attribute.unselectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiCirclePageIndicatorStyle = global::RssReader2.Resource.Attribute.vpiCirclePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiIconPageIndicatorStyle = global::RssReader2.Resource.Attribute.vpiIconPageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiLinePageIndicatorStyle = global::RssReader2.Resource.Attribute.vpiLinePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiTabPageIndicatorStyle = global::RssReader2.Resource.Attribute.vpiTabPageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiTitlePageIndicatorStyle = global::RssReader2.Resource.Attribute.vpiTitlePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiUnderlinePageIndicatorStyle = global::RssReader2.Resource.Attribute.vpiUnderlinePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_circle_indicator_centered = global::RssReader2.Resource.Boolean.default_circle_indicator_centered;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_circle_indicator_snap = global::RssReader2.Resource.Boolean.default_circle_indicator_snap;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_line_indicator_centered = global::RssReader2.Resource.Boolean.default_line_indicator_centered;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_title_indicator_selected_bold = global::RssReader2.Resource.Boolean.default_title_indicator_selected_bold;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_underline_indicator_fades = global::RssReader2.Resource.Boolean.default_underline_indicator_fades;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_circle_indicator_fill_color = global::RssReader2.Resource.Color.default_circle_indicator_fill_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_circle_indicator_page_color = global::RssReader2.Resource.Color.default_circle_indicator_page_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_circle_indicator_stroke_color = global::RssReader2.Resource.Color.default_circle_indicator_stroke_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_line_indicator_selected_color = global::RssReader2.Resource.Color.default_line_indicator_selected_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_line_indicator_unselected_color = global::RssReader2.Resource.Color.default_line_indicator_unselected_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_title_indicator_footer_color = global::RssReader2.Resource.Color.default_title_indicator_footer_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_title_indicator_selected_color = global::RssReader2.Resource.Color.default_title_indicator_selected_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_title_indicator_text_color = global::RssReader2.Resource.Color.default_title_indicator_text_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_underline_indicator_selected_color = global::RssReader2.Resource.Color.default_underline_indicator_selected_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__background_holo_dark = global::RssReader2.Resource.Color.vpi__background_holo_dark;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__background_holo_light = global::RssReader2.Resource.Color.vpi__background_holo_light;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_disabled_holo_dark = global::RssReader2.Resource.Color.vpi__bright_foreground_disabled_holo_dark;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_disabled_holo_light = global::RssReader2.Resource.Color.vpi__bright_foreground_disabled_holo_light;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_holo_dark = global::RssReader2.Resource.Color.vpi__bright_foreground_holo_dark;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_holo_light = global::RssReader2.Resource.Color.vpi__bright_foreground_holo_light;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_inverse_holo_dark = global::RssReader2.Resource.Color.vpi__bright_foreground_inverse_holo_dark;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_inverse_holo_light = global::RssReader2.Resource.Color.vpi__bright_foreground_inverse_holo_light;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__dark_theme = global::RssReader2.Resource.Color.vpi__dark_theme;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__light_theme = global::RssReader2.Resource.Color.vpi__light_theme;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_circle_indicator_radius = global::RssReader2.Resource.Dimension.default_circle_indicator_radius;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_circle_indicator_stroke_width = global::RssReader2.Resource.Dimension.default_circle_indicator_stroke_width;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_line_indicator_gap_width = global::RssReader2.Resource.Dimension.default_line_indicator_gap_width;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_line_indicator_line_width = global::RssReader2.Resource.Dimension.default_line_indicator_line_width;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_line_indicator_stroke_width = global::RssReader2.Resource.Dimension.default_line_indicator_stroke_width;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_clip_padding = global::RssReader2.Resource.Dimension.default_title_indicator_clip_padding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_indicator_height = global::RssReader2.Resource.Dimension.default_title_indicator_footer_indicator_height;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_indicator_underline_padding = global::RssReader2.Resource.Dimension.default_title_indicator_footer_indicator_underline_padding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_line_height = global::RssReader2.Resource.Dimension.default_title_indicator_footer_line_height;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_padding = global::RssReader2.Resource.Dimension.default_title_indicator_footer_padding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_text_size = global::RssReader2.Resource.Dimension.default_title_indicator_text_size;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_title_padding = global::RssReader2.Resource.Dimension.default_title_indicator_title_padding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_top_padding = global::RssReader2.Resource.Dimension.default_title_indicator_top_padding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_indicator = global::RssReader2.Resource.Drawable.vpi__tab_indicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_selected_focused_holo = global::RssReader2.Resource.Drawable.vpi__tab_selected_focused_holo;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_selected_holo = global::RssReader2.Resource.Drawable.vpi__tab_selected_holo;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_selected_pressed_holo = global::RssReader2.Resource.Drawable.vpi__tab_selected_pressed_holo;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_unselected_focused_holo = global::RssReader2.Resource.Drawable.vpi__tab_unselected_focused_holo;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_unselected_holo = global::RssReader2.Resource.Drawable.vpi__tab_unselected_holo;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_unselected_pressed_holo = global::RssReader2.Resource.Drawable.vpi__tab_unselected_pressed_holo;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.bottom = global::RssReader2.Resource.Id.bottom;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.none = global::RssReader2.Resource.Id.none;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.top = global::RssReader2.Resource.Id.top;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.triangle = global::RssReader2.Resource.Id.triangle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.underline = global::RssReader2.Resource.Id.underline;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_circle_indicator_orientation = global::RssReader2.Resource.Integer.default_circle_indicator_orientation;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_title_indicator_footer_indicator_style = global::RssReader2.Resource.Integer.default_title_indicator_footer_indicator_style;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_title_indicator_line_position = global::RssReader2.Resource.Integer.default_title_indicator_line_position;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_underline_indicator_fade_delay = global::RssReader2.Resource.Integer.default_underline_indicator_fade_delay;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_underline_indicator_fade_length = global::RssReader2.Resource.Integer.default_underline_indicator_fade_length;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.TextAppearance_TabPageIndicator = global::RssReader2.Resource.Style.TextAppearance_TabPageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.Theme_PageIndicatorDefaults = global::RssReader2.Resource.Style.Theme_PageIndicatorDefaults;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.Widget = global::RssReader2.Resource.Style.Widget;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.Widget_IconPageIndicator = global::RssReader2.Resource.Style.Widget_IconPageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.Widget_TabPageIndicator = global::RssReader2.Resource.Style.Widget_TabPageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator = global::RssReader2.Resource.Styleable.CirclePageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_android_background = global::RssReader2.Resource.Styleable.CirclePageIndicator_android_background;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_android_orientation = global::RssReader2.Resource.Styleable.CirclePageIndicator_android_orientation;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_centered = global::RssReader2.Resource.Styleable.CirclePageIndicator_centered;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_fillColor = global::RssReader2.Resource.Styleable.CirclePageIndicator_fillColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_pageColor = global::RssReader2.Resource.Styleable.CirclePageIndicator_pageColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_radius = global::RssReader2.Resource.Styleable.CirclePageIndicator_radius;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_snap = global::RssReader2.Resource.Styleable.CirclePageIndicator_snap;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_strokeColor = global::RssReader2.Resource.Styleable.CirclePageIndicator_strokeColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_strokeWidth = global::RssReader2.Resource.Styleable.CirclePageIndicator_strokeWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator = global::RssReader2.Resource.Styleable.LinePageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_android_background = global::RssReader2.Resource.Styleable.LinePageIndicator_android_background;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_centered = global::RssReader2.Resource.Styleable.LinePageIndicator_centered;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_gapWidth = global::RssReader2.Resource.Styleable.LinePageIndicator_gapWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_lineWidth = global::RssReader2.Resource.Styleable.LinePageIndicator_lineWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_selectedColor = global::RssReader2.Resource.Styleable.LinePageIndicator_selectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_strokeWidth = global::RssReader2.Resource.Styleable.LinePageIndicator_strokeWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_unselectedColor = global::RssReader2.Resource.Styleable.LinePageIndicator_unselectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator = global::RssReader2.Resource.Styleable.TitlePageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_android_background = global::RssReader2.Resource.Styleable.TitlePageIndicator_android_background;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_android_textColor = global::RssReader2.Resource.Styleable.TitlePageIndicator_android_textColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_android_textSize = global::RssReader2.Resource.Styleable.TitlePageIndicator_android_textSize;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_clipPadding = global::RssReader2.Resource.Styleable.TitlePageIndicator_clipPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerColor = global::RssReader2.Resource.Styleable.TitlePageIndicator_footerColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerIndicatorHeight = global::RssReader2.Resource.Styleable.TitlePageIndicator_footerIndicatorHeight;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerIndicatorStyle = global::RssReader2.Resource.Styleable.TitlePageIndicator_footerIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerIndicatorUnderlinePadding = global::RssReader2.Resource.Styleable.TitlePageIndicator_footerIndicatorUnderlinePadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerLineHeight = global::RssReader2.Resource.Styleable.TitlePageIndicator_footerLineHeight;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerPadding = global::RssReader2.Resource.Styleable.TitlePageIndicator_footerPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_linePosition = global::RssReader2.Resource.Styleable.TitlePageIndicator_linePosition;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_selectedBold = global::RssReader2.Resource.Styleable.TitlePageIndicator_selectedBold;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_selectedColor = global::RssReader2.Resource.Styleable.TitlePageIndicator_selectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_titlePadding = global::RssReader2.Resource.Styleable.TitlePageIndicator_titlePadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_topPadding = global::RssReader2.Resource.Styleable.TitlePageIndicator_topPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator = global::RssReader2.Resource.Styleable.UnderlinePageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_android_background = global::RssReader2.Resource.Styleable.UnderlinePageIndicator_android_background;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_fadeDelay = global::RssReader2.Resource.Styleable.UnderlinePageIndicator_fadeDelay;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_fadeLength = global::RssReader2.Resource.Styleable.UnderlinePageIndicator_fadeLength;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_fades = global::RssReader2.Resource.Styleable.UnderlinePageIndicator_fades;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_selectedColor = global::RssReader2.Resource.Styleable.UnderlinePageIndicator_selectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator = global::RssReader2.Resource.Styleable.ViewPagerIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle = global::RssReader2.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiIconPageIndicatorStyle = global::RssReader2.Resource.Styleable.ViewPagerIndicator_vpiIconPageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiLinePageIndicatorStyle = global::RssReader2.Resource.Styleable.ViewPagerIndicator_vpiLinePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiTabPageIndicatorStyle = global::RssReader2.Resource.Styleable.ViewPagerIndicator_vpiTabPageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiTitlePageIndicatorStyle = global::RssReader2.Resource.Styleable.ViewPagerIndicator_vpiTitlePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiUnderlinePageIndicatorStyle = global::RssReader2.Resource.Styleable.ViewPagerIndicator_vpiUnderlinePageIndicatorStyle;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public const int centered = 2130771974;
			
			// aapt resource value: 0x7f010022
			public const int circleColor = 2130772002;
			
			// aapt resource value: 0x7f010033
			public const int circularProgressBarStyle = 2130772019;
			
			// aapt resource value: 0x7f01002b
			public const int circular_gravity = 2130772011;
			
			// aapt resource value: 0x7f010031
			public const int circular_indeterminate = 2130772017;
			
			// aapt resource value: 0x7f010032
			public const int circular_indeterminate_interval = 2130772018;
			
			// aapt resource value: 0x7f01002e
			public const int circular_marker_progress = 2130772014;
			
			// aapt resource value: 0x7f01002d
			public const int circular_progress = 2130772013;
			
			// aapt resource value: 0x7f010030
			public const int circular_progress_background_color = 2130772016;
			
			// aapt resource value: 0x7f01002f
			public const int circular_progress_color = 2130772015;
			
			// aapt resource value: 0x7f01002c
			public const int circular_stroke_width = 2130772012;
			
			// aapt resource value: 0x7f010011
			public const int clipPadding = 2130771985;
			
			// aapt resource value: 0x7f01001d
			public const int fadeDelay = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int fadeLength = 2130771998;
			
			// aapt resource value: 0x7f01001c
			public const int fades = 2130771996;
			
			// aapt resource value: 0x7f01000a
			public const int fillColor = 2130771978;
			
			// aapt resource value: 0x7f010012
			public const int footerColor = 2130771986;
			
			// aapt resource value: 0x7f010015
			public const int footerIndicatorHeight = 2130771989;
			
			// aapt resource value: 0x7f010014
			public const int footerIndicatorStyle = 2130771988;
			
			// aapt resource value: 0x7f010016
			public const int footerIndicatorUnderlinePadding = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int footerLineHeight = 2130771987;
			
			// aapt resource value: 0x7f010017
			public const int footerPadding = 2130771991;
			
			// aapt resource value: 0x7f010010
			public const int gapWidth = 2130771984;
			
			// aapt resource value: 0x7f010029
			public const int indeterminate = 2130772009;
			
			// aapt resource value: 0x7f01002a
			public const int indeterminate_interval = 2130772010;
			
			// aapt resource value: 0x7f010027
			public const int innerSize = 2130772007;
			
			// aapt resource value: 0x7f010018
			public const int linePosition = 2130771992;
			
			// aapt resource value: 0x7f01000f
			public const int lineWidth = 2130771983;
			
			// aapt resource value: 0x7f010021
			public const int max = 2130772001;
			
			// aapt resource value: 0x7f01000b
			public const int pageColor = 2130771979;
			
			// aapt resource value: 0x7f010028
			public const int pinned = 2130772008;
			
			// aapt resource value: 0x7f010024
			public const int pinnedDrawable = 2130772004;
			
			// aapt resource value: 0x7f010020
			public const int progress = 2130772000;
			
			// aapt resource value: 0x7f01001f
			public const int progressButtonStyle = 2130771999;
			
			// aapt resource value: 0x7f010023
			public const int progressColor = 2130772003;
			
			// aapt resource value: 0x7f01000c
			public const int radius = 2130771980;
			
			// aapt resource value: 0x7f010019
			public const int selectedBold = 2130771993;
			
			// aapt resource value: 0x7f010007
			public const int selectedColor = 2130771975;
			
			// aapt resource value: 0x7f010026
			public const int shadowDrawable = 2130772006;
			
			// aapt resource value: 0x7f01000d
			public const int snap = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int strokeColor = 2130771982;
			
			// aapt resource value: 0x7f010008
			public const int strokeWidth = 2130771976;
			
			// aapt resource value: 0x7f01001a
			public const int titlePadding = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int topPadding = 2130771995;
			
			// aapt resource value: 0x7f010025
			public const int unpinnedDrawable = 2130772005;
			
			// aapt resource value: 0x7f010009
			public const int unselectedColor = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int vpiCirclePageIndicatorStyle = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int vpiIconPageIndicatorStyle = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int vpiLinePageIndicatorStyle = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int vpiTabPageIndicatorStyle = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int vpiTitlePageIndicatorStyle = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int vpiUnderlinePageIndicatorStyle = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f060000
			public const int default_circle_indicator_centered = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int default_circle_indicator_snap = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int default_line_indicator_centered = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int default_title_indicator_selected_bold = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int default_underline_indicator_fades = 2131099652;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050008
			public const int default_circle_indicator_fill_color = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int default_circle_indicator_page_color = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int default_circle_indicator_stroke_color = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int default_line_indicator_selected_color = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int default_line_indicator_unselected_color = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int default_title_indicator_footer_color = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int default_title_indicator_selected_color = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int default_title_indicator_text_color = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int default_underline_indicator_selected_color = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int progress_default_circle_color = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int progress_default_progress_color = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int refractored_background_dark = 2131034131;
			
			// aapt resource value: 0x7f050018
			public const int refractored_background_holo_dark = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int refractored_background_holo_light = 2131034137;
			
			// aapt resource value: 0x7f050014
			public const int refractored_background_light = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int refractored_bright_foreground_dark = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int refractored_bright_foreground_dark_disabled = 2131034135;
			
			// aapt resource value: 0x7f05001c
			public const int refractored_bright_foreground_disabled_holo_dark = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int refractored_bright_foreground_disabled_holo_light = 2131034141;
			
			// aapt resource value: 0x7f05001a
			public const int refractored_bright_foreground_holo_dark = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int refractored_bright_foreground_holo_light = 2131034139;
			
			// aapt resource value: 0x7f050016
			public const int refractored_bright_foreground_light = 2131034134;
			
			// aapt resource value: 0x7f05001f
			public const int refractored_dim_foreground_disabled_holo_dark = 2131034143;
			
			// aapt resource value: 0x7f050022
			public const int refractored_dim_foreground_disabled_holo_light = 2131034146;
			
			// aapt resource value: 0x7f05001e
			public const int refractored_dim_foreground_holo_dark = 2131034142;
			
			// aapt resource value: 0x7f050021
			public const int refractored_dim_foreground_holo_light = 2131034145;
			
			// aapt resource value: 0x7f050024
			public const int refractored_highlighted_text_holo_dark = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int refractored_highlighted_text_holo_light = 2131034149;
			
			// aapt resource value: 0x7f050020
			public const int refractored_hint_foreground_holo_dark = 2131034144;
			
			// aapt resource value: 0x7f050023
			public const int refractored_hint_foreground_holo_light = 2131034147;
			
			// aapt resource value: 0x7f05002f
			public const int refractored_holo_blue_bright = 2131034159;
			
			// aapt resource value: 0x7f050029
			public const int refractored_holo_blue_dark = 2131034153;
			
			// aapt resource value: 0x7f050026
			public const int refractored_holo_blue_light = 2131034150;
			
			// aapt resource value: 0x7f05002a
			public const int refractored_holo_green_dark = 2131034154;
			
			// aapt resource value: 0x7f050027
			public const int refractored_holo_green_light = 2131034151;
			
			// aapt resource value: 0x7f05002e
			public const int refractored_holo_orange_dark = 2131034158;
			
			// aapt resource value: 0x7f05002d
			public const int refractored_holo_orange_light = 2131034157;
			
			// aapt resource value: 0x7f05002c
			public const int refractored_holo_purple = 2131034156;
			
			// aapt resource value: 0x7f05002b
			public const int refractored_holo_red_dark = 2131034155;
			
			// aapt resource value: 0x7f050028
			public const int refractored_holo_red_light = 2131034152;
			
			// aapt resource value: 0x7f050030
			public const int standard_background = 2131034160;
			
			// aapt resource value: 0x7f050000
			public const int vpi__background_holo_dark = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int vpi__background_holo_light = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int vpi__bright_foreground_disabled_holo_dark = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int vpi__bright_foreground_disabled_holo_light = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int vpi__bright_foreground_holo_dark = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int vpi__bright_foreground_holo_light = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int vpi__bright_foreground_inverse_holo_dark = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int vpi__bright_foreground_inverse_holo_light = 2131034119;
			
			// aapt resource value: 0x7f050031
			public const int vpi__dark_theme = 2131034161;
			
			// aapt resource value: 0x7f050032
			public const int vpi__light_theme = 2131034162;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080000
			public const int default_circle_indicator_radius = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int default_circle_indicator_stroke_width = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int default_line_indicator_gap_width = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int default_line_indicator_line_width = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int default_line_indicator_stroke_width = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int default_title_indicator_clip_padding = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int default_title_indicator_footer_indicator_height = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int default_title_indicator_footer_indicator_underline_padding = 2131230728;
			
			// aapt resource value: 0x7f080006
			public const int default_title_indicator_footer_line_height = 2131230726;
			
			// aapt resource value: 0x7f080009
			public const int default_title_indicator_footer_padding = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int default_title_indicator_text_size = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int default_title_indicator_title_padding = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int default_title_indicator_top_padding = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int progress_inner_size = 2131230733;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int angry_birds_minion = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background_card = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int background_card_inverse = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bat_mobile = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bat_pod = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int drawer_shadow_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int drawer_shadow_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int flintmobile = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int hot_wheels_logo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_drawer_dark = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_drawer_light = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_launcher = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_menu_refresh = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int island_chopper = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int monoandroidsplash = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int news = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int pin_progress_pinned = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int pin_progress_shadow = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int pin_progress_unpinned = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int red_bird = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int rss_launcher = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int school_bus = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int scrubber_control_normal_holo = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int scrubber_control_pressed_holo = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int search = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int sharkruiser = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int tv_series_batmobile = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int vpi__tab_indicator = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int vpi__tab_selected_focused_holo = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int vpi__tab_selected_holo = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int vpi__tab_selected_pressed_holo = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int vpi__tab_unselected_focused_holo = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int vpi__tab_unselected_holo = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int vpi__tab_unselected_pressed_holo = 2130837537;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040025
			public const int About = 2130968613;
			
			// aapt resource value: 0x7f040024
			public const int Config = 2130968612;
			
			// aapt resource value: 0x7f040012
			public const int Image = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int Name = 2130968595;
			
			// aapt resource value: 0x7f04001d
			public const int Title = 2130968605;
			
			// aapt resource value: 0x7f040022
			public const int action_search = 2130968610;
			
			// aapt resource value: 0x7f040016
			public const int app_icon = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int app_title = 2130968599;
			
			// aapt resource value: 0x7f040003
			public const int bottom = 2130968579;
			
			// aapt resource value: 0x7f04001c
			public const int button_create_account = 2130968604;
			
			// aapt resource value: 0x7f040021
			public const int button_start_scan = 2130968609;
			
			// aapt resource value: 0x7f040005
			public const int center = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int center_horizontal = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int center_vertical = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int clip = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int clip_horizontal = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int clip_vertical = 2130968586;
			
			// aapt resource value: 0x7f04001f
			public const int content_frame = 2130968607;
			
			// aapt resource value: 0x7f040019
			public const int create_account_instructions = 2130968601;
			
			// aapt resource value: 0x7f040018
			public const int create_account_title = 2130968600;
			
			// aapt resource value: 0x7f04001e
			public const int drawer_layout = 2130968606;
			
			// aapt resource value: 0x7f04000b
			public const int end = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int fill = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int fill_horizontal = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int fill_vertical = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int left = 2130968591;
			
			// aapt resource value: 0x7f040020
			public const int left_drawer = 2130968608;
			
			// aapt resource value: 0x7f040014
			public const int my_cars_grid = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int news_list = 2130968597;
			
			// aapt resource value: 0x7f040000
			public const int none = 2130968576;
			
			// aapt resource value: 0x7f04001b
			public const int password_field = 2130968603;
			
			// aapt resource value: 0x7f040010
			public const int right = 2130968592;
			
			// aapt resource value: 0x7f040023
			public const int share_menu = 2130968611;
			
			// aapt resource value: 0x7f040011
			public const int start = 2130968593;
			
			// aapt resource value: 0x7f040004
			public const int top = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int triangle = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int underline = 2130968578;
			
			// aapt resource value: 0x7f04001a
			public const int user_field = 2130968602;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070006
			public const int circular_indeterminent_interval = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int default_circle_indicator_orientation = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int default_title_indicator_footer_indicator_style = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int default_title_indicator_line_position = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int default_underline_indicator_fade_delay = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int default_underline_indicator_fade_length = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int item_columns = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int progressbutton_indeterminent_interval = 2131165189;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int car_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_browse = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_mycars = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fragment_news = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int fragment_users_register = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int item = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int item_menu = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int page_home_view = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int scanner_view = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int menuBar = 2131427328;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0a0001
			public const int ApplicationName = 2131361793;
			
			// aapt resource value: 0x7f0a0000
			public const int Hello = 2131361792;
			
			// aapt resource value: 0x7f0a0002
			public const int app_title = 2131361794;
			
			// aapt resource value: 0x7f0a0007
			public const int button_create_button_text = 2131361799;
			
			// aapt resource value: 0x7f0a0009
			public const int button_scan_cancel = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int button_scan_torch = 2131361802;
			
			// aapt resource value: 0x7f0a0006
			public const int create_account = 2131361798;
			
			// aapt resource value: 0x7f0a0008
			public const int create_account_instructions = 2131361800;
			
			// aapt resource value: 0x7f0a0004
			public const int drawer_close = 2131361796;
			
			// aapt resource value: 0x7f0a0003
			public const int drawer_open = 2131361795;
			
			// aapt resource value: 0x7f0a000b
			public const int rss_fge = 2131361803;
			
			// aapt resource value: 0x7f0a0005
			public const int search = 2131361797;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090007
			public const int CircularProgressBar = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int CircularProgressBarLight = 2131296264;
			
			// aapt resource value: 0x7f09000b
			public const int Mono_Android_Theme_Splash = 2131296267;
			
			// aapt resource value: 0x7f090009
			public const int MyBaseTheme = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int MyTheme = 2131296266;
			
			// aapt resource value: 0x7f090005
			public const int ProgressButton = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int ProgressButton_Pin = 2131296262;
			
			// aapt resource value: 0x7f090003
			public const int TextAppearance_TabPageIndicator = 2131296259;
			
			// aapt resource value: 0x7f090000
			public const int Theme_PageIndicatorDefaults = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int Widget = 2131296257;
			
			// aapt resource value: 0x7f090004
			public const int Widget_IconPageIndicator = 2131296260;
			
			// aapt resource value: 0x7f090002
			public const int Widget_TabPageIndicator = 2131296258;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CirclePageIndicator = new int[]
			{
					16842948,
					16842964,
					2130771974,
					2130771976,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public const int CirclePageIndicator_android_background = 1;
			
			// aapt resource value: 0
			public const int CirclePageIndicator_android_orientation = 0;
			
			// aapt resource value: 2
			public const int CirclePageIndicator_centered = 2;
			
			// aapt resource value: 4
			public const int CirclePageIndicator_fillColor = 4;
			
			// aapt resource value: 5
			public const int CirclePageIndicator_pageColor = 5;
			
			// aapt resource value: 6
			public const int CirclePageIndicator_radius = 6;
			
			// aapt resource value: 7
			public const int CirclePageIndicator_snap = 7;
			
			// aapt resource value: 8
			public const int CirclePageIndicator_strokeColor = 8;
			
			// aapt resource value: 3
			public const int CirclePageIndicator_strokeWidth = 3;
			
			public static int[] HoloCircularProgressBar = new int[]
			{
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018};
			
			// aapt resource value: 0
			public const int HoloCircularProgressBar_circular_gravity = 0;
			
			// aapt resource value: 6
			public const int HoloCircularProgressBar_circular_indeterminate = 6;
			
			// aapt resource value: 7
			public const int HoloCircularProgressBar_circular_indeterminate_interval = 7;
			
			// aapt resource value: 3
			public const int HoloCircularProgressBar_circular_marker_progress = 3;
			
			// aapt resource value: 2
			public const int HoloCircularProgressBar_circular_progress = 2;
			
			// aapt resource value: 5
			public const int HoloCircularProgressBar_circular_progress_background_color = 5;
			
			// aapt resource value: 4
			public const int HoloCircularProgressBar_circular_progress_color = 4;
			
			// aapt resource value: 1
			public const int HoloCircularProgressBar_circular_stroke_width = 1;
			
			public static int[] LinePageIndicator = new int[]
			{
					16842964,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771983,
					2130771984};
			
			// aapt resource value: 0
			public const int LinePageIndicator_android_background = 0;
			
			// aapt resource value: 1
			public const int LinePageIndicator_centered = 1;
			
			// aapt resource value: 6
			public const int LinePageIndicator_gapWidth = 6;
			
			// aapt resource value: 5
			public const int LinePageIndicator_lineWidth = 5;
			
			// aapt resource value: 2
			public const int LinePageIndicator_selectedColor = 2;
			
			// aapt resource value: 3
			public const int LinePageIndicator_strokeWidth = 3;
			
			// aapt resource value: 4
			public const int LinePageIndicator_unselectedColor = 4;
			
			public static int[] ProgressButton = new int[]
			{
					16842970,
					16842981,
					16843534,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010};
			
			// aapt resource value: 1
			public const int ProgressButton_android_clickable = 1;
			
			// aapt resource value: 0
			public const int ProgressButton_android_focusable = 0;
			
			// aapt resource value: 2
			public const int ProgressButton_android_selectableItemBackground = 2;
			
			// aapt resource value: 5
			public const int ProgressButton_circleColor = 5;
			
			// aapt resource value: 12
			public const int ProgressButton_indeterminate = 12;
			
			// aapt resource value: 13
			public const int ProgressButton_indeterminate_interval = 13;
			
			// aapt resource value: 10
			public const int ProgressButton_innerSize = 10;
			
			// aapt resource value: 4
			public const int ProgressButton_max = 4;
			
			// aapt resource value: 11
			public const int ProgressButton_pinned = 11;
			
			// aapt resource value: 7
			public const int ProgressButton_pinnedDrawable = 7;
			
			// aapt resource value: 3
			public const int ProgressButton_progress = 3;
			
			// aapt resource value: 6
			public const int ProgressButton_progressColor = 6;
			
			// aapt resource value: 9
			public const int ProgressButton_shadowDrawable = 9;
			
			// aapt resource value: 8
			public const int ProgressButton_unpinnedDrawable = 8;
			
			public static int[] Theme = new int[]
			{
					2130772019};
			
			// aapt resource value: 0
			public const int Theme_circularProgressBarStyle = 0;
			
			public static int[] TitlePageIndicator = new int[]
			{
					16842901,
					16842904,
					16842964,
					2130771975,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995};
			
			// aapt resource value: 2
			public const int TitlePageIndicator_android_background = 2;
			
			// aapt resource value: 1
			public const int TitlePageIndicator_android_textColor = 1;
			
			// aapt resource value: 0
			public const int TitlePageIndicator_android_textSize = 0;
			
			// aapt resource value: 4
			public const int TitlePageIndicator_clipPadding = 4;
			
			// aapt resource value: 5
			public const int TitlePageIndicator_footerColor = 5;
			
			// aapt resource value: 8
			public const int TitlePageIndicator_footerIndicatorHeight = 8;
			
			// aapt resource value: 7
			public const int TitlePageIndicator_footerIndicatorStyle = 7;
			
			// aapt resource value: 9
			public const int TitlePageIndicator_footerIndicatorUnderlinePadding = 9;
			
			// aapt resource value: 6
			public const int TitlePageIndicator_footerLineHeight = 6;
			
			// aapt resource value: 10
			public const int TitlePageIndicator_footerPadding = 10;
			
			// aapt resource value: 11
			public const int TitlePageIndicator_linePosition = 11;
			
			// aapt resource value: 12
			public const int TitlePageIndicator_selectedBold = 12;
			
			// aapt resource value: 3
			public const int TitlePageIndicator_selectedColor = 3;
			
			// aapt resource value: 13
			public const int TitlePageIndicator_titlePadding = 13;
			
			// aapt resource value: 14
			public const int TitlePageIndicator_topPadding = 14;
			
			public static int[] UnderlinePageIndicator = new int[]
			{
					16842964,
					2130771975,
					2130771996,
					2130771997,
					2130771998};
			
			// aapt resource value: 0
			public const int UnderlinePageIndicator_android_background = 0;
			
			// aapt resource value: 3
			public const int UnderlinePageIndicator_fadeDelay = 3;
			
			// aapt resource value: 4
			public const int UnderlinePageIndicator_fadeLength = 4;
			
			// aapt resource value: 2
			public const int UnderlinePageIndicator_fades = 2;
			
			// aapt resource value: 1
			public const int UnderlinePageIndicator_selectedColor = 1;
			
			public static int[] ViewPagerIndicator = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
			
			// aapt resource value: 1
			public const int ViewPagerIndicator_vpiIconPageIndicatorStyle = 1;
			
			// aapt resource value: 2
			public const int ViewPagerIndicator_vpiLinePageIndicatorStyle = 2;
			
			// aapt resource value: 4
			public const int ViewPagerIndicator_vpiTabPageIndicatorStyle = 4;
			
			// aapt resource value: 3
			public const int ViewPagerIndicator_vpiTitlePageIndicatorStyle = 3;
			
			// aapt resource value: 5
			public const int ViewPagerIndicator_vpiUnderlinePageIndicatorStyle = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
